# Generated by Django 2.2.3 on 2019-07-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memes/')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('add_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-add_timestamp'],
            },
        ),
    ]
